name: brew test-bot

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  test-bot:
    name: Run tests
    strategy:
      matrix:
        os: [ macos-15-intel, macos-26 ]
    runs-on: ${{ matrix.os }}
    permissions:
      actions: read # to read artifacts
      checks: read # to read check results
      contents: read # to checkout code
      pull-requests: write # to add labels
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          # homebrew is designed to be difficult to pin for some reason, so we have pin it by cloning the repo at a specific revision,
          # which we do using a git submodule. https://github.com/Homebrew/actions/issues/874
          submodules: true

      - name: add brew to PATH
        run: echo "$PWD/brew/bin" >> $GITHUB_PATH

      - name: add tap
        env:
            tap: $GITHUB_REPOSITORY_OWNER/tap
        # . is needed to checkout the version from the current branch instead of main
        run: |
          brew tap $tap .
          brew trust $tap

      - name: install cask
        run: brew install rebased